const fs = require('fs');
let code = fs.readFileSync('src/server/routes/generate.ts', 'utf-8');

const target1 = `            const generatedUrl = await defaultImageService.generateBaseImage({
              prompt: promptEng,
              imageUrl: fluxBaseImageUrl,
              strength: fluxStrength
            });
            
            if (generatedUrl) {
                finalImageUrl = generatedUrl;
                customBlueprintCache.set(blueprintCacheKey, generatedUrl);
            } else {
                throw new Error("No image generated by Flux.");
            }`;

const replacement1 = `            const generatedBuffer = await defaultImageService.generateBaseImage({
              prompt: promptEng,
              imageUrl: fluxBaseImageUrl,
              strength: fluxStrength
            });
            
            if (generatedBuffer) {
                const uploadedUrl = await uploadBufferToFirebase(generatedBuffer, 'image/jpeg');
                finalImageUrl = uploadedUrl;
                customBlueprintCache.set(blueprintCacheKey, uploadedUrl);
            } else {
                throw new Error("No image generated by Flux.");
            }`;

code = code.replace(target1, replacement1);

const target2 = `      // Always run FaceSwap to ensure 100% facial feature retention
      try {
            console.log("Starting Virtual Try-On FaceSwap via ImageGenerationService... finalImageUrl:", finalImageUrl);
         
         const baseImageUrlForFal = finalImageUrl.startsWith('data:') ? await uploadImageToFal(finalImageUrl) : finalImageUrl;
         const swapImageUrlForFal = await swapImageUrlForFalPromise;
         
         if (baseImageUrlForFal.startsWith('data:') || swapImageUrlForFal.startsWith('data:')) {
             console.error("[generate-full] Error: Fal.storage upload failed during FaceSwap prep.");
             throw new Error("Не удалось загрузить изображение для обработки. Попробуйте ещё раз.");
         }
         
         swappedImageUrl = await defaultImageService.swapFace({
           baseImageUrl: baseImageUrlForFal,
           swapImageUrl: swapImageUrlForFal
         });
      } catch (error: any) {`;

const replacement2 = `      let imageBuffer: Buffer | null = null;
      // Always run FaceSwap to ensure 100% facial feature retention
      try {
            console.log("Starting Virtual Try-On FaceSwap via ImageGenerationService... finalImageUrl:", finalImageUrl);
         
         const baseImageUrlForFal = finalImageUrl.startsWith('data:') ? await uploadImageToFal(finalImageUrl) : finalImageUrl;
         const swapImageUrlForFal = await swapImageUrlForFalPromise;
         
         if (baseImageUrlForFal.startsWith('data:') || swapImageUrlForFal.startsWith('data:')) {
             console.error("[generate-full] Error: Fal.storage upload failed during FaceSwap prep.");
             throw new Error("Не удалось загрузить изображение для обработки. Попробуйте ещё раз.");
         }
         
         const swappedImageBuffer = await defaultImageService.swapFace({
           baseImageUrl: baseImageUrlForFal,
           swapImageUrl: swapImageUrlForFal
         });
         imageBuffer = swappedImageBuffer;
         swappedImageUrl = await uploadBufferToFirebase(swappedImageBuffer, 'image/jpeg');
      } catch (error: any) {`;

code = code.replace(target2, replacement2);

// Replace the fetch logic for swappedImageUrl using Regex to be safe
code = code.replace(/let tgFileId = null;[\s\S]*?console\.warn\("Failed to fetch swappedImage for storage:", e\);\s*}/, `let tgFileId = null;
      let sentViaTelegram = false;
      let contentType = 'image/jpeg';
      if (!imageBuffer || imageBuffer.byteLength < 5000) {
          throw new Error("FAL вернул невалидный файл (слишком маленький размер или неверный формат).");
      }`);

// Replace the background storage block
code = code.replace(/        \(\s*async\s*\(\)\s*=>\s*{\s*if\s*\(adminStorage\s*&&\s*imageBuffer\)\s*{[\s\S]*?console\.warn\("Async firebase storage error", storageErr\?\.message\);\s*}\s*}\s*}\)\(\)/, `        // Firebase async storage is removed because uploadBufferToFirebase handles it synchronously`);

fs.writeFileSync('src/server/routes/generate.ts', code);
console.log("Done");
